
eureka:
  client:
    serviceUrl:
      defaultZone: http://vymage-service-registry.cfapps.io/eureka/
  instance:
    hostname: ${vcap.application.uris[0]}
    nonSecurePort: 80

spring:
  cloud:
    client:
      hostname: ${vcap.application.uris[0]}
